/**
 * Template Registry (Task 5.1)
 *
 * Manages built-in export templates and provides template discovery.
 * Templates can be system-wide, tenant-specific, or project-specific.
 */

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

/**
 * Built-in system templates
 * These are registered on first use or via seed script
 */
const SYSTEM_TEMPLATES = {
  // Payment Application - Standard Excel Format
  PAYMENT_APP_STANDARD_XLSX: {
    code: 'PAYMENT_APP_STANDARD_XLSX',
    name: 'Payment Application - Standard Excel',
    description: 'Standard payment application format in Excel with line items',
    category: 'PAYMENT_APPLICATION',
    format: 'XLSX',
    scope: 'SYSTEM',
    config: {
      dateFormat: 'DD/MM/YYYY',
      currencyFormat: { currency: 'GBP', decimals: 2, symbol: '£' },
      includeLineItems: true,
      includeRetention: true,
    },
    fieldMappings: {
      'Application Number': 'applicationNo',
      'Application Date': 'applicationDate',
      'Period Start': 'periodStart',
      'Period End': 'periodEnd',
      'Value This Period': 'claimedThisPeriod',
      'Value to Date': 'cumulativeGross',
      'Retention This Period': 'retentionThisPeriod',
      'Retention to Date': 'retentionCumulative',
      'Net Amount': 'netAmount',
      'VAT': 'vatAmount',
      'Total': 'totalAmount',
      'Contractor': 'project.name',
      'Contract': 'contract.contractRef',
    },
    isDefault: true,
  },

  // Payment Application - CSV Format
  PAYMENT_APP_STANDARD_CSV: {
    code: 'PAYMENT_APP_STANDARD_CSV',
    name: 'Payment Application - CSV',
    description: 'Payment application data in CSV format for import to other systems',
    category: 'PAYMENT_APPLICATION',
    format: 'CSV',
    scope: 'SYSTEM',
    config: {
      dateFormat: 'YYYY-MM-DD',
      delimiter: ',',
      includeHeaders: true,
    },
    fieldMappings: {
      'app_number': 'applicationNo',
      'app_date': 'applicationDate',
      'period_start': 'periodStart',
      'period_end': 'periodEnd',
      'value_this_period': 'claimedThisPeriod',
      'value_to_date': 'cumulativeGross',
      'retention': 'retentionCumulative',
      'net_amount': 'netAmount',
      'project_id': 'projectId',
      'contract_id': 'contractId',
    },
    isDefault: true,
  },

  // Payment Application - PDF
  PAYMENT_APP_STANDARD_PDF: {
    code: 'PAYMENT_APP_STANDARD_PDF',
    name: 'Payment Application - Standard PDF',
    description: 'Professional PDF payment application document',
    category: 'PAYMENT_APPLICATION',
    format: 'PDF',
    scope: 'SYSTEM',
    config: {
      dateFormat: 'DD/MM/YYYY',
      currencyFormat: { currency: 'GBP', decimals: 2, symbol: '£' },
      includeLineItems: true,
      includeRetention: true,
      logoUrl: null, // Can be customized per tenant
      footerText: 'Payment Application - Generated by ERP System',
    },
    fieldMappings: {
      'applicationNo': 'applicationNo',
      'applicationDate': 'applicationDate',
      'periodStart': 'periodStart',
      'periodEnd': 'periodEnd',
      'claimedThisPeriod': 'claimedThisPeriod',
      'cumulativeGross': 'cumulativeGross',
      'retentionThisPeriod': 'retentionThisPeriod',
      'retentionCumulative': 'retentionCumulative',
      'netAmount': 'netAmount',
      'projectName': 'project.name',
      'contractRef': 'contract.contractRef',
    },
    isDefault: true,
  },

  // CVR Report - Excel
  CVR_REPORT_STANDARD_XLSX: {
    code: 'CVR_REPORT_STANDARD_XLSX',
    name: 'CVR Report - Standard Excel',
    description: 'Cost Value Reconciliation report in Excel format',
    category: 'CVR_REPORT',
    format: 'XLSX',
    scope: 'SYSTEM',
    config: {
      dateFormat: 'DD/MM/YYYY',
      currencyFormat: { currency: 'GBP', decimals: 2, symbol: '£' },
      includeCostBreakdown: true,
      includeValueBreakdown: true,
      includeMarginAnalysis: true,
    },
    fieldMappings: {
      'Report Date': 'reportDate',
      'Period End': 'periodEnd',
      'Total Value': 'value.totalValue',
      'Total Cost': 'cost.totalCost',
      'Gross Margin': 'results.grossMargin',
      'Gross Margin %': 'results.grossMarginPercentage',
      'Labour Cost': 'cost.labour',
      'Materials Cost': 'cost.materials',
      'Subcontractor Cost': 'cost.subcontractors',
      'Plant Cost': 'cost.plant',
      'Overheads': 'cost.overheads',
    },
    isDefault: true,
  },

  // Retention Statement - PDF
  RETENTION_STATEMENT_PDF: {
    code: 'RETENTION_STATEMENT_PDF',
    name: 'Retention Statement - PDF',
    description: 'Retention statement showing held and released amounts',
    category: 'RETENTION_STATEMENT',
    format: 'PDF',
    scope: 'SYSTEM',
    config: {
      dateFormat: 'DD/MM/YYYY',
      currencyFormat: { currency: 'GBP', decimals: 2, symbol: '£' },
    },
    fieldMappings: {
      'statementDate': 'statementDate',
      'totalRetentionHeld': 'totalHeld',
      'totalRetentionReleased': 'totalReleased',
      'netRetention': 'netRetention',
      'projectName': 'project.name',
      'contractRef': 'contract.contractRef',
    },
    isDefault: true,
  },
};

/**
 * Register a system template in the database
 */
async function registerSystemTemplate(templateData) {
  const existing = await prisma.exportTemplate.findUnique({
    where: {
      tenantId_code: {
        tenantId: null,
        code: templateData.code,
      },
    },
  });

  if (existing) {
    // Update existing template
    return prisma.exportTemplate.update({
      where: { id: existing.id },
      data: {
        ...templateData,
        tenantId: null, // System templates have no tenantId
        updatedAt: new Date(),
      },
    });
  }

  // Create new template
  return prisma.exportTemplate.create({
    data: {
      ...templateData,
      tenantId: null, // System templates have no tenantId
    },
  });
}

/**
 * Register all system templates
 */
async function registerAllSystemTemplates() {
  const results = [];

  for (const [key, template] of Object.entries(SYSTEM_TEMPLATES)) {
    try {
      const result = await registerSystemTemplate(template);
      results.push({ code: template.code, status: 'registered', id: result.id });
    } catch (error) {
      results.push({ code: template.code, status: 'failed', error: error.message });
    }
  }

  return results;
}

/**
 * Get template for a specific main contractor
 *
 * Some main contractors require specific formats. This function finds
 * the appropriate template based on the MC name or ID.
 */
async function getMainContractorTemplate(tenantId, mainContractorName, category, format) {
  // Try to find MC-specific template
  const mcTemplate = await prisma.exportTemplate.findFirst({
    where: {
      tenantId,
      mainContractorName: {
        contains: mainContractorName,
        mode: 'insensitive',
      },
      category,
      format,
      isActive: true,
    },
  });

  if (mcTemplate) return mcTemplate;

  // Fall back to default template
  return getDefaultTemplate(tenantId, category, format);
}

/**
 * Get default template (from export service)
 */
async function getDefaultTemplate(tenantId, category, format) {
  // First try tenant-specific default
  let template = await prisma.exportTemplate.findFirst({
    where: {
      tenantId,
      category,
      format,
      isDefault: true,
      isActive: true,
    },
  });

  // Fall back to system default
  if (!template) {
    template = await prisma.exportTemplate.findFirst({
      where: {
        tenantId: null,
        category,
        format,
        isDefault: true,
        isActive: true,
        scope: 'SYSTEM',
      },
    });
  }

  return template;
}

/**
 * Clone a system template for tenant customization
 */
async function cloneTemplateForTenant(templateId, tenantId, customizations = {}) {
  const sourceTemplate = await prisma.exportTemplate.findUnique({
    where: { id: templateId },
  });

  if (!sourceTemplate) {
    throw new Error('Source template not found');
  }

  // Generate new code for the cloned template
  const newCode = `${sourceTemplate.code}_${tenantId.substring(0, 8).toUpperCase()}`;

  return prisma.exportTemplate.create({
    data: {
      tenantId,
      name: customizations.name || `${sourceTemplate.name} (Custom)`,
      code: newCode,
      description: customizations.description || sourceTemplate.description,
      category: sourceTemplate.category,
      format: sourceTemplate.format,
      scope: 'TENANT',
      config: customizations.config || sourceTemplate.config,
      fieldMappings: customizations.fieldMappings || sourceTemplate.fieldMappings,
      isActive: true,
      isDefault: customizations.isDefault || false,
    },
  });
}

module.exports = {
  SYSTEM_TEMPLATES,
  registerSystemTemplate,
  registerAllSystemTemplates,
  getMainContractorTemplate,
  getDefaultTemplate,
  cloneTemplateForTenant,
};
